### ISSUE TITLE
Docker-Gen Cannot Generate Configuration

### ISSUE THREAD

**Issue by maxexcloo** [jwilder/docker-gen#15]
When the output file is set to be written to a volume, docker-gen is unable to create the configuration there due to what appears to be a hard link error.

**Comment by quokkamole** [comment]
"Unable to create dest file /etc/nginx/conf.d/default.conf: rename /etc/nginx/conf.d/docker-gen"

I got this problem when launching (via docker-compose) from a shared folder on a windows host (linux guest in virtualbox) presumably due to associated file manipulation limitations as outlined above. Solution: run on the guest fs.
