### ISSUE TITLE
Can dockergen run as a non-root user?

### ISSUE THREAD

**Issue by lhridley** [jwilder/docker-gen#232]
I believe the answer to this is "no" but if dockergen can run as a non-root user and work with nginx (which I have running as non-root), can someone please explain how?

**Comment by jwilder** [comment]
Yes.  The user running `docker-gen` just needs to have read permissions on the docker unix socket (`/var/run/docker.sock`) file or access to the TLS keys if using TCP sockets.  For the former, usually adding them to the `docker` group (if that exists works).

**Comment by zuhrulumam** [comment]
Sorry to bother you.. @lhridley did you solve running docker-gen with non-root user (with nginx running non-root user)?

Thanks.

**Comment by inieves** [comment]
It's been a while since any activity here, being closed and all.  Worth commenting that I am now experimenting with a new docker daemon JSON setting:

"userns-remap" : "default"

This is supposed to remap PIDs such that root in the host container is not root on the host.

I am noticing that this setting yields a docker.sock (in docker-gen) with:
srw-rw---- 1 nobody nogroup  0 Sep 19 11:02 docker.sock=

Even after adding the container root to the "nogroup" group, I am not able to get docker-gen to connect to the docker sock.  I will look more into this, but wanted to add at least this update.
